#!/bin/sh

program_exists () {
	type "$1" &> /dev/null ;
}

CONVERT=''

if program_exists gm; then
	CONVERT='gm convert'
fi

if [ -z "$CONVERT" ] && program_exists convert; then
	CONVERT='convert'
fi

if [ -z "$CONVERT" ]; then
	echo "Please install GraphicsMagick or ImageMagick"
	exit 1
fi

for f in $@; do
	if [[ $f == *@3x* ]]; then
		FNAME_2x=${f/@3x/@2x}
		FNAME_1x=${f/@3x/}
		echo "Converting $f to $FNAME_2x ..."
		$CONVERT -resize 66.666%x66.666% "$f" "$FNAME_2x"
		echo "Converting $f to $FNAME_1x ..."
		$CONVERT -resize 33.333%x33.333% "$f" "$FNAME_1x"
	fi
done