#!/bin/bash

program_exists ()
{
	type "$1" &> /dev/null ;
}

usage()
{
	local PROG_NAME=`basename $0`
	echo "Usage: $PROG_NAME fitfile [gpxfile]"
}

main()
{
	set -e
	#set -o xtrace

	if ! program_exists gpsbabel; then
		echo "Please install gpsbabel"
		exit 2
	fi

	if [ "$#" -lt 1 ]; then
		usage
		exit 1
	fi

	local FIT_FILE=$1
	local GPX_FILE=$2

	if [ ! $GPX_FILE ];then
   		GPX_FILE=${FIT_FILE/fit/gpx}
	fi

	gpsbabel -i garmin_fit -f "$FIT_FILE" -o gpx -F "$GPX_FILE"

 	#set +o xtrace
}

main "$@"

