#!/bin/bash

program_exists ()
{
	type "$1" &> /dev/null ;
}

usage()
{
	local PROG_NAME=`basename $0`
	echo "Usage: $PROG_NAME gpxfile"
}

main()
{
	set -e

	if ! program_exists gpsbabel; then
		echo "Please install gpsbabel"
		exit 1
	fi

	if [ "$#" -lt 1 ]; then
		usage
		exit 1
	fi

	local GPX_FILE=$1

	gpsbabel -i gpx -f "$GPX_FILE" -o gpx -F "$GPX_FILE"
}

main "$@"
