#!/bin/bash

main()
{
	if [ "$#" -ne 1 ]; then
	    echo "Please provide branch name to merge from"
	    exit -1
	fi

	branch=$1

	git fetch origin $branch:$branch
	git merge origin/$branch
}

main "$@"

