#!/bin/bash -e

main()
{
	branchName=$(git symbolic-ref --short HEAD)

	git checkout master

	git pull

	if git merge ${branchName} ; then
		echo
		echo "Merge succeeded. Now you may do git push"
		echo
	else
		echo
		echo "Merge failed."
		echo
	fi
}

main "$@"

