#!/bin/bash

program_exists ()
{
	type "$1" &> /dev/null ;
}

usage()
{
	local PROG_NAME=`basename $0`
	echo "Usage: $PROG_NAME gpxfile [kmlfile]"
}

main()
{
	set -e
	#set -o xtrace

	if ! program_exists gpsbabel; then
		echo "Please install gpsbabel"
		exit 2
	fi

	if [ "$#" -lt 1 ]; then
		usage
		exit 1
	fi

	local KML_FILE=$1
	local GPX_FILE=$2

	if [ ! $GPX_FILE ];then
   		GPX_FILE=${KML_FILE/gpx/kml}
	fi

	gpsbabel -i gpx -f "$KML_FILE" -o kml -F "$GPX_FILE"

 	#set +o xtrace
}

main "$@"

