#!/bin/bash

program_exists ()
{
	type "$1" &> /dev/null ;
}

usage()
{
	local PROG_NAME=`basename $0`
	echo "Usage: $PROG_NAME gpxfile [kmlfile]"
}

main()
{
	set -e
	#set -o xtrace

	if ! program_exists gpsbabel; then
		echo "Please install gpsbabel"
		exit 2
	fi

	if [ "$#" -lt 1 ]; then
		usage
		exit 1
	fi

	local GPX_IN_FILE=$1
	local GPX_OUT_FILE=$2

	if [ ! $GPX_OUT_FILE ];then
   		GPX_OUT_FILE=${GPX_IN_FILE}_out.gpx
	fi

	gpsbabel -i gpx -f "$GPX_IN_FILE" -o gpx -F "$GPX_OUT_FILE"

 	#set +o xtrace
}

main "$@"

