#!/bin/bash

main()
{
	set -e

	if [ "$#" -lt 1 ]; then
		echo "Please provide repo name"
		exit 1
	fi

	USER='ivanzoid'
	PASS=`security find-internet-password -s bitbucket.org -w`
	REPO_NAME=$1

	curl --user $USER:$PASS "https://api.bitbucket.org/1.0/repositories/" --data name=$REPO_NAME --data is_private=true

	echo
	echo
	echo "git@bitbucket.org:${USER}/${REPO_NAME}.git"
}

main "$@"





