#!/bin/bash

main()
{
	BEST_FILES=$(lsXnviewBestFiles .)

	if [ -z "$BEST_FILES" ]; then
    	return
	fi

	mkdir -p '#Best'

	for f in $BEST_FILES; do
		echo "$f..."
		mv "$f" "#Best/$f"
	done
}

main "$@"
