#!/bin/bash

main()
{
	PAN_FILES=$(lsXnviewPanFiles .)

	if [ -z "$PAN_FILES" ]; then
    	return
	fi

	mkdir -p '#Pan'

	for f in $PAN_FILES; do
		echo "$f..."
		mv "$f" "#Pan/$f"
	done
}

main "$@"
