#!/bin/sh

HOSTNAME=`echo $@ | sed s/.*@//`

set_bg () {
#	return
  osascript -e "tell application \"Terminal\" to set background color of window 1 to $1" > /dev/null 2>&1 &
}

on_exit () {
  set_bg "{65535, 65535, 65535, 65535}"
}
trap on_exit EXIT

set_bg "{65535, 60000, 60000, 65535}"

/usr/bin/ssh "$@"
