#!/bin/bash

set -e

program_exists () {
	type "$1" &> /dev/null ;
}

if program_exists go; then
	echo "export GOROOT=/usr/local/opt/go/libexec" > $HOME/.go.conf
	echo "export GOPATH=\"$HOME/Go\"" >> $HOME/.go.conf
fi

